<?php


/**
 * Implementes hook_requirements()
 */
function fastly_streamline_access_requirements($phase) {
  $requirements = [];
  if ($phase === 'runtime') {
    $config = \Drupal::config('fastly_streamline_access.settings');
    if (empty($config->get('acl_name')) || empty($config->get('passphrase'))) {

      $url = \Drupal\Core\Url::fromRoute('fastly_streamline_access.config_form');
      $link = \Drupal\Core\Link::fromTextAndUrl("FSA admin page", $url);

      $requirements['fastly_streamline_access'] = [
        'title' => t('OPS IF'),
        'value' => t('Setup Required'),
        'severity' => REQUIREMENT_ERROR,
        'description' => t(
          'OPSIF has not been set up correctly - visit ' . $link->toString() . ' to configure'
        ),
      ];
    }
  }

  return $requirements;
}
